### ISSUE TITLE
Node can't build app, UnhandledPromise

### ISSUE THREAD

**Issue by DobroAlex** [gdomaradzki/focus-budget-manager#24]
I'm using instruction from README and i stuck at step: node services
cmd output is:
node services
consign v0.1.6 Initialized in services
+ .\BudgetManagerAPI\app\setup\index.js
+ .\BudgetManagerAPI\app\api\auth.js
+ .\BudgetManagerAPI\app\api\budget.js
+ .\BudgetManagerAPI\app\api\client.js
+ .\BudgetManagerAPI\app\api\user.js
+ .\BudgetManagerAPI\app\routes\auth.js
+ .\BudgetManagerAPI\app\routes\budget.js
+ .\BudgetManagerAPI\app\routes\client.js
+ .\BudgetManagerAPI\app\routes\user.js
BudgetManagerAPI running on 3001
Disconnected from BudgetManager database
Connection to BudgetManager database failed: MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
(node:10812) UnhandledPromiseRejectionWarning: MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (C:\Users\alexk\Desktop\focus-budget-manager-master\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (C:\Users\alexk\Desktop\focus-budget-manager-master\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (C:\Users\alexk\Desktop\focus-budget-manager-master\node_modules\mongodb-core\lib\connection\connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:10812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DobroAlex** [comment]
Solved. There was some problem with Mongo, I just had to reinstall it & everything is fine now
